### ISSUE TITLE
selection jumps unpredictably after moving through choices with keyboard

### ISSUE THREAD

**Issue by fenugrec** [lxqt/lxqt-runner#169] opened 2021-01-16 22:20 UTC
##### Expected Behavior
Invoking the runner with `alt+F2` , typing a few letters to identify the program, then moving down the list with arrow keys then pressing enter , often results in unpleasant surprises when the runner changes the selection automatically to the top of the list , a few milliseconds before pressing enter. 

##### Current Behavior
Here's a 50kB video capture of an example: 
https://user-images.githubusercontent.com/10098613/104824315-9ced6980-581e-11eb-98c0-d33a586f17be.mp4

keypress sequence was 
1- `alt-F2`
1- type `gimp`
1- press `down` a few times

And a fraction of a second later, the cursor moves back up to the top of the list ! In this case it didn't matter being the same program, but often it's a different one, and by then I'm already physically pressing the Enter key and it's too late.

##### Possible Solution
Not sure... maybe disable automatic selection changes after any key press ? The first keypress pretty much announces the user's intent to choose an entry via the keyboard IMO

##### Context
General annoyance.

##### System Information
Has been doing this for many past versions. I just finally got annoyed enough to file an issue.

* Distribution & Version: archlinux 
* Kernel: 5.4.84
* Qt Version: 5.15.2
* liblxqt Version: 0.16.0-1
* lxqt-build-tools Version: 
* lxqt-runner v 0.16.0-1

**Comment by tsujan** [comment] 2021-01-16 23:02
I can reproduce the issue by pressing the arrow-down key immediately after typing: the selection goes down and up.

It would be annoying to me too if I used Runner regularly. It's definitely a bug.

**Comment by stefonarch** [comment] 2021-01-17 08:06
> It would be annoying to me too if I used Runner regularly. It's definitely a bug.

I use only runner but hardly use the arrow keys, just typing and enter, never noticed this.

**Comment by palinek** [comment] 2021-01-18 08:16
IMO this is caused by adding the timer to wait before searching after typing.
I personally don't like the timer and think the delay should be at least configurable (to allow disabling it completely).

**Comment by tsujan** [comment] 2021-01-18 08:22
The timer can be made configurable but if the issue is caused by its code, the code has a bug thaat should be fixed -- they're different things.

Haven't has time to check it yet...

**Comment by tsujan** [comment] 2021-01-24 09:41
I checked the code, found the cause and fixed it here. It wasn't related to the timer. The code changed the current item when it shouldn't — in `Dialog::dataChanged()`.

Will make a PR after some tests.

**Closed** 2021-02-10 08:35 UTC
Labels: bug

**Comment by fenugrec** [comment] 2021-02-10 12:45
Thanks, looking forward to test !

**Comment by tsujan** [comment] 2021-02-10 12:48
> looking forward to test !

@fenugrec 
I merged the PR; the fix is in the git source.
